title: Sokoli na komínech
description: >-
  Záchrana kriticky ohroženého sokola stěhovavého. Pomoc sokolům ve městech a
  průmyslových areálech.
url: 'https://www.sokolinakominech.cz'
logo: /media/sysli_na_vinici_logo_200.jpg
lang: cs_CZ
lang_alternatives: []
author: alka-wildlife
facebook:
  admins: 1133305906
  app_id: 145375228868712
  publisher: 269120446533000
social:
  links:
    - 'https://www.facebook.com/AlkaWildlife'
  name: 'ALKA Wildlife, o.p.s.'
webmaster_verifications:
  google: o27dsTgYww0bzXVmTZ_CgadoY8QtzpDMgo-bVSgH3OM
google_analytics: G-4ZMCQP7J5D
